# configuration file for Jekyll theme

# build settings
title: Mark's CIT 85 Public Site
description: My public site for CIT 85 HTML and CSS Spring 2025
show_downloads: true

# themes

# Tactile
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
